server:
  port: 8080
#Credentials are defined per microservice
spring:
  datasource:
    schema: classpath*:db/mysql/schema.sql
    data: classpath*:db/mysql/data.sql
    platform: mysql
    initialization-mode: always
  cloud:
    services:
      registrationMethod: direct
    gcp:
      sql:
        database-name: service-instance-db
        instance-connection-name: pgtm-avetter:us-central1:customers-db-gcp



management:
  metrics:
    export:
      wavefront:
        uri: ${vcap.services.wavefront.credentials.uri}
        api-token: ${vcap.services.wavefront.credentials.api-token}

wavefront:
  application:
    name: ${vcap.services.wavefront.credentials.application-name}
  freemium-account: false


