spring:
  datasource:
    url: ${vcap.services.customers-db.credentials.jdbcUrl}&queryInterceptors=brave.mysql8.TracingQueryInterceptor&exceptionInterceptors=brave.mysql8.TracingExceptionInterceptor&zipkinServiceName=customers-db-gcp
    username: ${vcap.services.customers-db-gcp.credentials.username:root}
    password: ${vcap.services.customers-db-gcp.credentials.password:petclinic}
  cloud:
    gcp:
      sql:
        database-name: service_instance_db
