spring:
  datasource:
    url: ${vcap.services.instance_name.credentials.jdbcUrl}&queryInterceptors=brave.mysql8.TracingQueryInterceptor&exceptionInterceptors=brave.mysql8.TracingExceptionInterceptor&zipkinServiceName=${vcap.services.instance_name}
    #url: ${vcap.services.customers-db.credentials.jdbcUrl}
    username: ${vcap.services.instance_name.credentials.username:root}
    password: ${vcap.services.instance_namecredentials.password:petclinic}
