spring:
  datasource:
    url: ${vcap.services.customers-db-tac.credentials.jdbcUrl}&queryInterceptors=brave.mysql8.TracingQueryInterceptor&exceptionInterceptors=brave.mysql8.TracingExceptionInterceptor&zipkinServiceName=customers-db-tac
    username: ${vcap.services.customers-db-tac.credentials.username:root}
    password: ${vcap.services.customers-db-tac.credentials.password:petclinic}
